// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/algorithm.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExecuteRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AlgorithmId    string                 `protobuf:"bytes,1,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	Mode           string                 `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	Params         map[string]string      `protobuf:"bytes,3,rep,name=params,proto3" json:"params,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	InputSource    *InputSource           `protobuf:"bytes,4,opt,name=input_source,json=inputSource,proto3" json:"input_source,omitempty"`
	WebhookUrl     string                 `protobuf:"bytes,5,opt,name=webhook_url,json=webhookUrl,proto3" json:"webhook_url,omitempty"`
	ForceRefresh   bool                   `protobuf:"varint,6,opt,name=force_refresh,json=forceRefresh,proto3" json:"force_refresh,omitempty"`
	ResourceConfig *ResourceConfig        `protobuf:"bytes,7,opt,name=resource_config,json=resourceConfig,proto3" json:"resource_config,omitempty"`
	TimeoutSeconds int32                  `protobuf:"varint,8,opt,name=timeout_seconds,json=timeoutSeconds,proto3" json:"timeout_seconds,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ExecuteRequest) Reset() {
	*x = ExecuteRequest{}
	mi := &file_proto_algorithm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRequest) ProtoMessage() {}

func (x *ExecuteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_algorithm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRequest) Descriptor() ([]byte, []int) {
	return file_proto_algorithm_proto_rawDescGZIP(), []int{0}
}

func (x *ExecuteRequest) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *ExecuteRequest) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *ExecuteRequest) GetParams() map[string]string {
	if x != nil {
		return x.Params
	}
	return nil
}

func (x *ExecuteRequest) GetInputSource() *InputSource {
	if x != nil {
		return x.InputSource
	}
	return nil
}

func (x *ExecuteRequest) GetWebhookUrl() string {
	if x != nil {
		return x.WebhookUrl
	}
	return ""
}

func (x *ExecuteRequest) GetForceRefresh() bool {
	if x != nil {
		return x.ForceRefresh
	}
	return false
}

func (x *ExecuteRequest) GetResourceConfig() *ResourceConfig {
	if x != nil {
		return x.ResourceConfig
	}
	return nil
}

func (x *ExecuteRequest) GetTimeoutSeconds() int32 {
	if x != nil {
		return x.TimeoutSeconds
	}
	return 0
}

type InputSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputSource) Reset() {
	*x = InputSource{}
	mi := &file_proto_algorithm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputSource) ProtoMessage() {}

func (x *InputSource) ProtoReflect() protoreflect.Message {
	mi := &file_proto_algorithm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputSource.ProtoReflect.Descriptor instead.
func (*InputSource) Descriptor() ([]byte, []int) {
	return file_proto_algorithm_proto_rawDescGZIP(), []int{1}
}

func (x *InputSource) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *InputSource) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type ResourceConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuLimit      float32                `protobuf:"fixed32,1,opt,name=cpu_limit,json=cpuLimit,proto3" json:"cpu_limit,omitempty"`
	MemoryLimit   string                 `protobuf:"bytes,2,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResourceConfig) Reset() {
	*x = ResourceConfig{}
	mi := &file_proto_algorithm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResourceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceConfig) ProtoMessage() {}

func (x *ResourceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_algorithm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceConfig.ProtoReflect.Descriptor instead.
func (*ResourceConfig) Descriptor() ([]byte, []int) {
	return file_proto_algorithm_proto_rawDescGZIP(), []int{2}
}

func (x *ResourceConfig) GetCpuLimit() float32 {
	if x != nil {
		return x.CpuLimit
	}
	return 0
}

func (x *ResourceConfig) GetMemoryLimit() string {
	if x != nil {
		return x.MemoryLimit
	}
	return ""
}

type ExecuteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ResultUrl     string                 `protobuf:"bytes,3,opt,name=result_url,json=resultUrl,proto3" json:"result_url,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteResponse) Reset() {
	*x = ExecuteResponse{}
	mi := &file_proto_algorithm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteResponse) ProtoMessage() {}

func (x *ExecuteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_algorithm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteResponse.ProtoReflect.Descriptor instead.
func (*ExecuteResponse) Descriptor() ([]byte, []int) {
	return file_proto_algorithm_proto_rawDescGZIP(), []int{3}
}

func (x *ExecuteResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *ExecuteResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ExecuteResponse) GetResultUrl() string {
	if x != nil {
		return x.ResultUrl
	}
	return ""
}

func (x *ExecuteResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetJobStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusRequest) Reset() {
	*x = GetJobStatusRequest{}
	mi := &file_proto_algorithm_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusRequest) ProtoMessage() {}

func (x *GetJobStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_algorithm_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusRequest.ProtoReflect.Descriptor instead.
func (*GetJobStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_algorithm_proto_rawDescGZIP(), []int{4}
}

func (x *GetJobStatusRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetJobStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ResultUrl     string                 `protobuf:"bytes,3,opt,name=result_url,json=resultUrl,proto3" json:"result_url,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	CostTimeMs    int32                  `protobuf:"varint,6,opt,name=cost_time_ms,json=costTimeMs,proto3" json:"cost_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobStatusResponse) Reset() {
	*x = GetJobStatusResponse{}
	mi := &file_proto_algorithm_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobStatusResponse) ProtoMessage() {}

func (x *GetJobStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_algorithm_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobStatusResponse.ProtoReflect.Descriptor instead.
func (*GetJobStatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_algorithm_proto_rawDescGZIP(), []int{5}
}

func (x *GetJobStatusResponse) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *GetJobStatusResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetJobStatusResponse) GetResultUrl() string {
	if x != nil {
		return x.ResultUrl
	}
	return ""
}

func (x *GetJobStatusResponse) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *GetJobStatusResponse) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *GetJobStatusResponse) GetCostTimeMs() int32 {
	if x != nil {
		return x.CostTimeMs
	}
	return 0
}

var File_proto_algorithm_proto protoreflect.FileDescriptor

const file_proto_algorithm_proto_rawDesc = "" +
	"\n" +
	"\x15proto/algorithm.proto\x12\x06api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa6\x03\n" +
	"\x0eExecuteRequest\x12!\n" +
	"\falgorithm_id\x18\x01 \x01(\tR\valgorithmId\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12:\n" +
	"\x06params\x18\x03 \x03(\v2\".api.v1.ExecuteRequest.ParamsEntryR\x06params\x126\n" +
	"\finput_source\x18\x04 \x01(\v2\x13.api.v1.InputSourceR\vinputSource\x12\x1f\n" +
	"\vwebhook_url\x18\x05 \x01(\tR\n" +
	"webhookUrl\x12#\n" +
	"\rforce_refresh\x18\x06 \x01(\bR\fforceRefresh\x12?\n" +
	"\x0fresource_config\x18\a \x01(\v2\x16.api.v1.ResourceConfigR\x0eresourceConfig\x12'\n" +
	"\x0ftimeout_seconds\x18\b \x01(\x05R\x0etimeoutSeconds\x1a9\n" +
	"\vParamsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"3\n" +
	"\vInputSource\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\"P\n" +
	"\x0eResourceConfig\x12\x1b\n" +
	"\tcpu_limit\x18\x01 \x01(\x02R\bcpuLimit\x12!\n" +
	"\fmemory_limit\x18\x02 \x01(\tR\vmemoryLimit\"y\n" +
	"\x0fExecuteResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"result_url\x18\x03 \x01(\tR\tresultUrl\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\",\n" +
	"\x13GetJobStatusRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\xfe\x01\n" +
	"\x14GetJobStatusResponse\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"result_url\x18\x03 \x01(\tR\tresultUrl\x129\n" +
	"\n" +
	"started_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12 \n" +
	"\fcost_time_ms\x18\x06 \x01(\x05R\n" +
	"costTimeMs2\xf7\x01\n" +
	"\x10AlgorithmService\x12y\n" +
	"\x10ExecuteAlgorithm\x12\x16.api.v1.ExecuteRequest\x1a\x17.api.v1.ExecuteResponse\"4\x82\xd3\xe4\x93\x02.:\x01*\")/api/v1/algorithms/{algorithm_id}/execute\x12h\n" +
	"\fGetJobStatus\x12\x1b.api.v1.GetJobStatusRequest\x1a\x1c.api.v1.GetJobStatusResponse\"\x1d\x82\xd3\xe4\x93\x02\x17\x12\x15/api/v1/jobs/{job_id}B\x1eZ\x1calgorithm-platform/api/v1;v1b\x06proto3"

var (
	file_proto_algorithm_proto_rawDescOnce sync.Once
	file_proto_algorithm_proto_rawDescData []byte
)

func file_proto_algorithm_proto_rawDescGZIP() []byte {
	file_proto_algorithm_proto_rawDescOnce.Do(func() {
		file_proto_algorithm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_algorithm_proto_rawDesc), len(file_proto_algorithm_proto_rawDesc)))
	})
	return file_proto_algorithm_proto_rawDescData
}

var file_proto_algorithm_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_proto_algorithm_proto_goTypes = []any{
	(*ExecuteRequest)(nil),        // 0: api.v1.ExecuteRequest
	(*InputSource)(nil),           // 1: api.v1.InputSource
	(*ResourceConfig)(nil),        // 2: api.v1.ResourceConfig
	(*ExecuteResponse)(nil),       // 3: api.v1.ExecuteResponse
	(*GetJobStatusRequest)(nil),   // 4: api.v1.GetJobStatusRequest
	(*GetJobStatusResponse)(nil),  // 5: api.v1.GetJobStatusResponse
	nil,                           // 6: api.v1.ExecuteRequest.ParamsEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_proto_algorithm_proto_depIdxs = []int32{
	6, // 0: api.v1.ExecuteRequest.params:type_name -> api.v1.ExecuteRequest.ParamsEntry
	1, // 1: api.v1.ExecuteRequest.input_source:type_name -> api.v1.InputSource
	2, // 2: api.v1.ExecuteRequest.resource_config:type_name -> api.v1.ResourceConfig
	7, // 3: api.v1.GetJobStatusResponse.started_at:type_name -> google.protobuf.Timestamp
	7, // 4: api.v1.GetJobStatusResponse.finished_at:type_name -> google.protobuf.Timestamp
	0, // 5: api.v1.AlgorithmService.ExecuteAlgorithm:input_type -> api.v1.ExecuteRequest
	4, // 6: api.v1.AlgorithmService.GetJobStatus:input_type -> api.v1.GetJobStatusRequest
	3, // 7: api.v1.AlgorithmService.ExecuteAlgorithm:output_type -> api.v1.ExecuteResponse
	5, // 8: api.v1.AlgorithmService.GetJobStatus:output_type -> api.v1.GetJobStatusResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_proto_algorithm_proto_init() }
func file_proto_algorithm_proto_init() {
	if File_proto_algorithm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_algorithm_proto_rawDesc), len(file_proto_algorithm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_algorithm_proto_goTypes,
		DependencyIndexes: file_proto_algorithm_proto_depIdxs,
		MessageInfos:      file_proto_algorithm_proto_msgTypes,
	}.Build()
	File_proto_algorithm_proto = out.File
	file_proto_algorithm_proto_goTypes = nil
	file_proto_algorithm_proto_depIdxs = nil
}
