// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/management.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAlgorithmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Platform      string                 `protobuf:"bytes,4,opt,name=platform,proto3" json:"platform,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	Entrypoint    string                 `protobuf:"bytes,6,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlgorithmRequest) Reset() {
	*x = CreateAlgorithmRequest{}
	mi := &file_proto_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlgorithmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlgorithmRequest) ProtoMessage() {}

func (x *CreateAlgorithmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlgorithmRequest.ProtoReflect.Descriptor instead.
func (*CreateAlgorithmRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAlgorithmRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAlgorithmRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAlgorithmRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CreateAlgorithmRequest) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *CreateAlgorithmRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateAlgorithmRequest) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

type UpdateAlgorithmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlgorithmRequest) Reset() {
	*x = UpdateAlgorithmRequest{}
	mi := &file_proto_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlgorithmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlgorithmRequest) ProtoMessage() {}

func (x *UpdateAlgorithmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlgorithmRequest.ProtoReflect.Descriptor instead.
func (*UpdateAlgorithmRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateAlgorithmRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAlgorithmRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAlgorithmRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateAlgorithmRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type Algorithm struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Language         string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Platform         string                 `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	Category         string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Entrypoint       string                 `protobuf:"bytes,7,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	CurrentVersionId string                 `protobuf:"bytes,8,opt,name=current_version_id,json=currentVersionId,proto3" json:"current_version_id,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Algorithm) Reset() {
	*x = Algorithm{}
	mi := &file_proto_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Algorithm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Algorithm) ProtoMessage() {}

func (x *Algorithm) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Algorithm.ProtoReflect.Descriptor instead.
func (*Algorithm) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{2}
}

func (x *Algorithm) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Algorithm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Algorithm) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Algorithm) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Algorithm) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *Algorithm) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Algorithm) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *Algorithm) GetCurrentVersionId() string {
	if x != nil {
		return x.CurrentVersionId
	}
	return ""
}

func (x *Algorithm) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Algorithm) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListAlgorithmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlgorithmsRequest) Reset() {
	*x = ListAlgorithmsRequest{}
	mi := &file_proto_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlgorithmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlgorithmsRequest) ProtoMessage() {}

func (x *ListAlgorithmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlgorithmsRequest.ProtoReflect.Descriptor instead.
func (*ListAlgorithmsRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{3}
}

func (x *ListAlgorithmsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListAlgorithmsRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ListAlgorithmsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAlgorithmsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListAlgorithmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithms    []*Algorithm           `protobuf:"bytes,1,rep,name=algorithms,proto3" json:"algorithms,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlgorithmsResponse) Reset() {
	*x = ListAlgorithmsResponse{}
	mi := &file_proto_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlgorithmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlgorithmsResponse) ProtoMessage() {}

func (x *ListAlgorithmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlgorithmsResponse.ProtoReflect.Descriptor instead.
func (*ListAlgorithmsResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{4}
}

func (x *ListAlgorithmsResponse) GetAlgorithms() []*Algorithm {
	if x != nil {
		return x.Algorithms
	}
	return nil
}

func (x *ListAlgorithmsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type CreateVersionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AlgorithmId      string                 `protobuf:"bytes,1,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	SourceCodeZipUrl string                 `protobuf:"bytes,2,opt,name=source_code_zip_url,json=sourceCodeZipUrl,proto3" json:"source_code_zip_url,omitempty"`
	CommitMessage    string                 `protobuf:"bytes,3,opt,name=commit_message,json=commitMessage,proto3" json:"commit_message,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateVersionRequest) Reset() {
	*x = CreateVersionRequest{}
	mi := &file_proto_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVersionRequest) ProtoMessage() {}

func (x *CreateVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVersionRequest.ProtoReflect.Descriptor instead.
func (*CreateVersionRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{5}
}

func (x *CreateVersionRequest) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *CreateVersionRequest) GetSourceCodeZipUrl() string {
	if x != nil {
		return x.SourceCodeZipUrl
	}
	return ""
}

func (x *CreateVersionRequest) GetCommitMessage() string {
	if x != nil {
		return x.CommitMessage
	}
	return ""
}

type Version struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AlgorithmId   string                 `protobuf:"bytes,2,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	VersionNumber int32                  `protobuf:"varint,3,opt,name=version_number,json=versionNumber,proto3" json:"version_number,omitempty"`
	MinioPath     string                 `protobuf:"bytes,4,opt,name=minio_path,json=minioPath,proto3" json:"minio_path,omitempty"`
	CommitMessage string                 `protobuf:"bytes,5,opt,name=commit_message,json=commitMessage,proto3" json:"commit_message,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_proto_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{6}
}

func (x *Version) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Version) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *Version) GetVersionNumber() int32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

func (x *Version) GetMinioPath() string {
	if x != nil {
		return x.MinioPath
	}
	return ""
}

func (x *Version) GetCommitMessage() string {
	if x != nil {
		return x.CommitMessage
	}
	return ""
}

func (x *Version) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RollbackVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlgorithmId   string                 `protobuf:"bytes,1,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	VersionId     string                 `protobuf:"bytes,2,opt,name=version_id,json=versionId,proto3" json:"version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackVersionRequest) Reset() {
	*x = RollbackVersionRequest{}
	mi := &file_proto_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackVersionRequest) ProtoMessage() {}

func (x *RollbackVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackVersionRequest.ProtoReflect.Descriptor instead.
func (*RollbackVersionRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{7}
}

func (x *RollbackVersionRequest) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *RollbackVersionRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

type UploadDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	MinioPath     string                 `protobuf:"bytes,3,opt,name=minio_path,json=minioPath,proto3" json:"minio_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDataRequest) Reset() {
	*x = UploadDataRequest{}
	mi := &file_proto_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDataRequest) ProtoMessage() {}

func (x *UploadDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDataRequest.ProtoReflect.Descriptor instead.
func (*UploadDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{8}
}

func (x *UploadDataRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadDataRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UploadDataRequest) GetMinioPath() string {
	if x != nil {
		return x.MinioPath
	}
	return ""
}

type UploadDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,json=fileId,proto3" json:"file_id,omitempty"`
	MinioUrl      string                 `protobuf:"bytes,2,opt,name=minio_url,json=minioUrl,proto3" json:"minio_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDataResponse) Reset() {
	*x = UploadDataResponse{}
	mi := &file_proto_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDataResponse) ProtoMessage() {}

func (x *UploadDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDataResponse.ProtoReflect.Descriptor instead.
func (*UploadDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{9}
}

func (x *UploadDataResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadDataResponse) GetMinioUrl() string {
	if x != nil {
		return x.MinioUrl
	}
	return ""
}

type ListPresetDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPresetDataRequest) Reset() {
	*x = ListPresetDataRequest{}
	mi := &file_proto_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPresetDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPresetDataRequest) ProtoMessage() {}

func (x *ListPresetDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPresetDataRequest.ProtoReflect.Descriptor instead.
func (*ListPresetDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{10}
}

func (x *ListPresetDataRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListPresetDataRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPresetDataRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListPresetDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*PresetData          `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPresetDataResponse) Reset() {
	*x = ListPresetDataResponse{}
	mi := &file_proto_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPresetDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPresetDataResponse) ProtoMessage() {}

func (x *ListPresetDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPresetDataResponse.ProtoReflect.Descriptor instead.
func (*ListPresetDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{11}
}

func (x *ListPresetDataResponse) GetFiles() []*PresetData {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListPresetDataResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type PresetData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	MinioUrl      string                 `protobuf:"bytes,4,opt,name=minio_url,json=minioUrl,proto3" json:"minio_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresetData) Reset() {
	*x = PresetData{}
	mi := &file_proto_management_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresetData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresetData) ProtoMessage() {}

func (x *PresetData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresetData.ProtoReflect.Descriptor instead.
func (*PresetData) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{12}
}

func (x *PresetData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PresetData) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *PresetData) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *PresetData) GetMinioUrl() string {
	if x != nil {
		return x.MinioUrl
	}
	return ""
}

func (x *PresetData) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlgorithmId   string                 `protobuf:"bytes,1,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_proto_management_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{13}
}

func (x *ListJobsRequest) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *ListJobsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListJobsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListJobsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobSummary          `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_proto_management_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{14}
}

func (x *ListJobsResponse) GetJobs() []*JobSummary {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type JobSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AlgorithmId   string                 `protobuf:"bytes,2,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	AlgorithmName string                 `protobuf:"bytes,3,opt,name=algorithm_name,json=algorithmName,proto3" json:"algorithm_name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CostTimeMs    int32                  `protobuf:"varint,6,opt,name=cost_time_ms,json=costTimeMs,proto3" json:"cost_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSummary) Reset() {
	*x = JobSummary{}
	mi := &file_proto_management_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSummary) ProtoMessage() {}

func (x *JobSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSummary.ProtoReflect.Descriptor instead.
func (*JobSummary) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{15}
}

func (x *JobSummary) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobSummary) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *JobSummary) GetAlgorithmName() string {
	if x != nil {
		return x.AlgorithmName
	}
	return ""
}

func (x *JobSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *JobSummary) GetCostTimeMs() int32 {
	if x != nil {
		return x.CostTimeMs
	}
	return 0
}

type GetJobDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobDetailRequest) Reset() {
	*x = GetJobDetailRequest{}
	mi := &file_proto_management_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobDetailRequest) ProtoMessage() {}

func (x *GetJobDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobDetailRequest.ProtoReflect.Descriptor instead.
func (*GetJobDetailRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{16}
}

func (x *GetJobDetailRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,json=jobId,proto3" json:"job_id,omitempty"`
	AlgorithmId   string                 `protobuf:"bytes,2,opt,name=algorithm_id,json=algorithmId,proto3" json:"algorithm_id,omitempty"`
	AlgorithmName string                 `protobuf:"bytes,3,opt,name=algorithm_name,json=algorithmName,proto3" json:"algorithm_name,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	InputParams   string                 `protobuf:"bytes,6,opt,name=input_params,json=inputParams,proto3" json:"input_params,omitempty"`
	InputUrl      string                 `protobuf:"bytes,7,opt,name=input_url,json=inputUrl,proto3" json:"input_url,omitempty"`
	OutputUrl     string                 `protobuf:"bytes,8,opt,name=output_url,json=outputUrl,proto3" json:"output_url,omitempty"`
	LogUrl        string                 `protobuf:"bytes,9,opt,name=log_url,json=logUrl,proto3" json:"log_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	CostTimeMs    int32                  `protobuf:"varint,13,opt,name=cost_time_ms,json=costTimeMs,proto3" json:"cost_time_ms,omitempty"`
	WorkerId      string                 `protobuf:"bytes,14,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobDetail) Reset() {
	*x = JobDetail{}
	mi := &file_proto_management_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDetail) ProtoMessage() {}

func (x *JobDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDetail.ProtoReflect.Descriptor instead.
func (*JobDetail) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{17}
}

func (x *JobDetail) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobDetail) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *JobDetail) GetAlgorithmName() string {
	if x != nil {
		return x.AlgorithmName
	}
	return ""
}

func (x *JobDetail) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *JobDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobDetail) GetInputParams() string {
	if x != nil {
		return x.InputParams
	}
	return ""
}

func (x *JobDetail) GetInputUrl() string {
	if x != nil {
		return x.InputUrl
	}
	return ""
}

func (x *JobDetail) GetOutputUrl() string {
	if x != nil {
		return x.OutputUrl
	}
	return ""
}

func (x *JobDetail) GetLogUrl() string {
	if x != nil {
		return x.LogUrl
	}
	return ""
}

func (x *JobDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *JobDetail) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *JobDetail) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *JobDetail) GetCostTimeMs() int32 {
	if x != nil {
		return x.CostTimeMs
	}
	return 0
}

func (x *JobDetail) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

var File_proto_management_proto protoreflect.FileDescriptor

const file_proto_management_proto_rawDesc = "" +
	"\n" +
	"\x16proto/management.proto\x12\x06api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc2\x01\n" +
	"\x16CreateAlgorithmRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12\x1a\n" +
	"\bplatform\x18\x04 \x01(\tR\bplatform\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x06 \x01(\tR\n" +
	"entrypoint\"z\n" +
	"\x16UpdateAlgorithmRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\"\xe9\x02\n" +
	"\tAlgorithm\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12\x1a\n" +
	"\bplatform\x18\x05 \x01(\tR\bplatform\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\a \x01(\tR\n" +
	"entrypoint\x12,\n" +
	"\x12current_version_id\x18\b \x01(\tR\x10currentVersionId\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x80\x01\n" +
	"\x15ListAlgorithmsRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"a\n" +
	"\x16ListAlgorithmsResponse\x121\n" +
	"\n" +
	"algorithms\x18\x01 \x03(\v2\x11.api.v1.AlgorithmR\n" +
	"algorithms\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x8f\x01\n" +
	"\x14CreateVersionRequest\x12!\n" +
	"\falgorithm_id\x18\x01 \x01(\tR\valgorithmId\x12-\n" +
	"\x13source_code_zip_url\x18\x02 \x01(\tR\x10sourceCodeZipUrl\x12%\n" +
	"\x0ecommit_message\x18\x03 \x01(\tR\rcommitMessage\"\xe4\x01\n" +
	"\aVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\falgorithm_id\x18\x02 \x01(\tR\valgorithmId\x12%\n" +
	"\x0eversion_number\x18\x03 \x01(\x05R\rversionNumber\x12\x1d\n" +
	"\n" +
	"minio_path\x18\x04 \x01(\tR\tminioPath\x12%\n" +
	"\x0ecommit_message\x18\x05 \x01(\tR\rcommitMessage\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"Z\n" +
	"\x16RollbackVersionRequest\x12!\n" +
	"\falgorithm_id\x18\x01 \x01(\tR\valgorithmId\x12\x1d\n" +
	"\n" +
	"version_id\x18\x02 \x01(\tR\tversionId\"j\n" +
	"\x11UploadDataRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1d\n" +
	"\n" +
	"minio_path\x18\x03 \x01(\tR\tminioPath\"J\n" +
	"\x12UploadDataResponse\x12\x17\n" +
	"\afile_id\x18\x01 \x01(\tR\x06fileId\x12\x1b\n" +
	"\tminio_url\x18\x02 \x01(\tR\bminioUrl\"d\n" +
	"\x15ListPresetDataRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"X\n" +
	"\x16ListPresetDataResponse\x12(\n" +
	"\x05files\x18\x01 \x03(\v2\x12.api.v1.PresetDataR\x05files\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xac\x01\n" +
	"\n" +
	"PresetData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1b\n" +
	"\tminio_url\x18\x04 \x01(\tR\bminioUrl\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"}\n" +
	"\x0fListJobsRequest\x12!\n" +
	"\falgorithm_id\x18\x01 \x01(\tR\valgorithmId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x04 \x01(\x05R\bpageSize\"P\n" +
	"\x10ListJobsResponse\x12&\n" +
	"\x04jobs\x18\x01 \x03(\v2\x12.api.v1.JobSummaryR\x04jobs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\xe2\x01\n" +
	"\n" +
	"JobSummary\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12!\n" +
	"\falgorithm_id\x18\x02 \x01(\tR\valgorithmId\x12%\n" +
	"\x0ealgorithm_name\x18\x03 \x01(\tR\ralgorithmName\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12 \n" +
	"\fcost_time_ms\x18\x06 \x01(\x05R\n" +
	"costTimeMs\",\n" +
	"\x13GetJobDetailRequest\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\"\x82\x04\n" +
	"\tJobDetail\x12\x15\n" +
	"\x06job_id\x18\x01 \x01(\tR\x05jobId\x12!\n" +
	"\falgorithm_id\x18\x02 \x01(\tR\valgorithmId\x12%\n" +
	"\x0ealgorithm_name\x18\x03 \x01(\tR\ralgorithmName\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12!\n" +
	"\finput_params\x18\x06 \x01(\tR\vinputParams\x12\x1b\n" +
	"\tinput_url\x18\a \x01(\tR\binputUrl\x12\x1d\n" +
	"\n" +
	"output_url\x18\b \x01(\tR\toutputUrl\x12\x17\n" +
	"\alog_url\x18\t \x01(\tR\x06logUrl\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"started_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x12;\n" +
	"\vfinished_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\x12 \n" +
	"\fcost_time_ms\x18\r \x01(\x05R\n" +
	"costTimeMs\x12\x1b\n" +
	"\tworker_id\x18\x0e \x01(\tR\bworkerId2\xe4\a\n" +
	"\x11ManagementService\x12c\n" +
	"\x0fCreateAlgorithm\x12\x1e.api.v1.CreateAlgorithmRequest\x1a\x11.api.v1.Algorithm\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/algorithms\x12h\n" +
	"\x0fUpdateAlgorithm\x12\x1e.api.v1.UpdateAlgorithmRequest\x1a\x11.api.v1.Algorithm\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/api/v1/algorithms/{id}\x12k\n" +
	"\x0eListAlgorithms\x12\x1d.api.v1.ListAlgorithmsRequest\x1a\x1e.api.v1.ListAlgorithmsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/algorithms\x12u\n" +
	"\rCreateVersion\x12\x1c.api.v1.CreateVersionRequest\x1a\x0f.api.v1.Version\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/api/v1/algorithms/{algorithm_id}/versions\x12\x8e\x01\n" +
	"\x0fRollbackVersion\x12\x1e.api.v1.RollbackVersionRequest\x1a\x11.api.v1.Algorithm\"H\x82\xd3\xe4\x93\x02B\"@/api/v1/algorithms/{algorithm_id}/versions/{version_id}/rollback\x12i\n" +
	"\x10UploadPresetData\x12\x19.api.v1.UploadDataRequest\x1a\x1a.api.v1.UploadDataResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/data/upload\x12e\n" +
	"\x0eListPresetData\x12\x1d.api.v1.ListPresetDataRequest\x1a\x1e.api.v1.ListPresetDataResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/data\x12S\n" +
	"\bListJobs\x12\x17.api.v1.ListJobsRequest\x1a\x18.api.v1.ListJobsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/jobs\x12d\n" +
	"\fGetJobDetail\x12\x1b.api.v1.GetJobDetailRequest\x1a\x11.api.v1.JobDetail\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/jobs/{job_id}/detailB\x1eZ\x1calgorithm-platform/api/v1;v1b\x06proto3"

var (
	file_proto_management_proto_rawDescOnce sync.Once
	file_proto_management_proto_rawDescData []byte
)

func file_proto_management_proto_rawDescGZIP() []byte {
	file_proto_management_proto_rawDescOnce.Do(func() {
		file_proto_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_management_proto_rawDesc), len(file_proto_management_proto_rawDesc)))
	})
	return file_proto_management_proto_rawDescData
}

var file_proto_management_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_proto_management_proto_goTypes = []any{
	(*CreateAlgorithmRequest)(nil), // 0: api.v1.CreateAlgorithmRequest
	(*UpdateAlgorithmRequest)(nil), // 1: api.v1.UpdateAlgorithmRequest
	(*Algorithm)(nil),              // 2: api.v1.Algorithm
	(*ListAlgorithmsRequest)(nil),  // 3: api.v1.ListAlgorithmsRequest
	(*ListAlgorithmsResponse)(nil), // 4: api.v1.ListAlgorithmsResponse
	(*CreateVersionRequest)(nil),   // 5: api.v1.CreateVersionRequest
	(*Version)(nil),                // 6: api.v1.Version
	(*RollbackVersionRequest)(nil), // 7: api.v1.RollbackVersionRequest
	(*UploadDataRequest)(nil),      // 8: api.v1.UploadDataRequest
	(*UploadDataResponse)(nil),     // 9: api.v1.UploadDataResponse
	(*ListPresetDataRequest)(nil),  // 10: api.v1.ListPresetDataRequest
	(*ListPresetDataResponse)(nil), // 11: api.v1.ListPresetDataResponse
	(*PresetData)(nil),             // 12: api.v1.PresetData
	(*ListJobsRequest)(nil),        // 13: api.v1.ListJobsRequest
	(*ListJobsResponse)(nil),       // 14: api.v1.ListJobsResponse
	(*JobSummary)(nil),             // 15: api.v1.JobSummary
	(*GetJobDetailRequest)(nil),    // 16: api.v1.GetJobDetailRequest
	(*JobDetail)(nil),              // 17: api.v1.JobDetail
	(*timestamppb.Timestamp)(nil),  // 18: google.protobuf.Timestamp
}
var file_proto_management_proto_depIdxs = []int32{
	18, // 0: api.v1.Algorithm.created_at:type_name -> google.protobuf.Timestamp
	18, // 1: api.v1.Algorithm.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 2: api.v1.ListAlgorithmsResponse.algorithms:type_name -> api.v1.Algorithm
	18, // 3: api.v1.Version.created_at:type_name -> google.protobuf.Timestamp
	12, // 4: api.v1.ListPresetDataResponse.files:type_name -> api.v1.PresetData
	18, // 5: api.v1.PresetData.created_at:type_name -> google.protobuf.Timestamp
	15, // 6: api.v1.ListJobsResponse.jobs:type_name -> api.v1.JobSummary
	18, // 7: api.v1.JobSummary.created_at:type_name -> google.protobuf.Timestamp
	18, // 8: api.v1.JobDetail.created_at:type_name -> google.protobuf.Timestamp
	18, // 9: api.v1.JobDetail.started_at:type_name -> google.protobuf.Timestamp
	18, // 10: api.v1.JobDetail.finished_at:type_name -> google.protobuf.Timestamp
	0,  // 11: api.v1.ManagementService.CreateAlgorithm:input_type -> api.v1.CreateAlgorithmRequest
	1,  // 12: api.v1.ManagementService.UpdateAlgorithm:input_type -> api.v1.UpdateAlgorithmRequest
	3,  // 13: api.v1.ManagementService.ListAlgorithms:input_type -> api.v1.ListAlgorithmsRequest
	5,  // 14: api.v1.ManagementService.CreateVersion:input_type -> api.v1.CreateVersionRequest
	7,  // 15: api.v1.ManagementService.RollbackVersion:input_type -> api.v1.RollbackVersionRequest
	8,  // 16: api.v1.ManagementService.UploadPresetData:input_type -> api.v1.UploadDataRequest
	10, // 17: api.v1.ManagementService.ListPresetData:input_type -> api.v1.ListPresetDataRequest
	13, // 18: api.v1.ManagementService.ListJobs:input_type -> api.v1.ListJobsRequest
	16, // 19: api.v1.ManagementService.GetJobDetail:input_type -> api.v1.GetJobDetailRequest
	2,  // 20: api.v1.ManagementService.CreateAlgorithm:output_type -> api.v1.Algorithm
	2,  // 21: api.v1.ManagementService.UpdateAlgorithm:output_type -> api.v1.Algorithm
	4,  // 22: api.v1.ManagementService.ListAlgorithms:output_type -> api.v1.ListAlgorithmsResponse
	6,  // 23: api.v1.ManagementService.CreateVersion:output_type -> api.v1.Version
	2,  // 24: api.v1.ManagementService.RollbackVersion:output_type -> api.v1.Algorithm
	9,  // 25: api.v1.ManagementService.UploadPresetData:output_type -> api.v1.UploadDataResponse
	11, // 26: api.v1.ManagementService.ListPresetData:output_type -> api.v1.ListPresetDataResponse
	14, // 27: api.v1.ManagementService.ListJobs:output_type -> api.v1.ListJobsResponse
	17, // 28: api.v1.ManagementService.GetJobDetail:output_type -> api.v1.JobDetail
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_proto_management_proto_init() }
func file_proto_management_proto_init() {
	if File_proto_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_management_proto_rawDesc), len(file_proto_management_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_management_proto_goTypes,
		DependencyIndexes: file_proto_management_proto_depIdxs,
		MessageInfos:      file_proto_management_proto_msgTypes,
	}.Build()
	File_proto_management_proto = out.File
	file_proto_management_proto_goTypes = nil
	file_proto_management_proto_depIdxs = nil
}
