// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/management.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Platform int32

const (
	Platform_PLATFORM_DOCKER         Platform = 0
	Platform_PLATFORM_LINUX_X86_64   Platform = 1
	Platform_PLATFORM_LINUX_ARM64    Platform = 2
	Platform_PLATFORM_WINDOWS_X86_64 Platform = 3
	Platform_PLATFORM_MACOS_ARM64    Platform = 4
)

// Enum value maps for Platform.
var (
	Platform_name = map[int32]string{
		0: "PLATFORM_DOCKER",
		1: "PLATFORM_LINUX_X86_64",
		2: "PLATFORM_LINUX_ARM64",
		3: "PLATFORM_WINDOWS_X86_64",
		4: "PLATFORM_MACOS_ARM64",
	}
	Platform_value = map[string]int32{
		"PLATFORM_DOCKER":         0,
		"PLATFORM_LINUX_X86_64":   1,
		"PLATFORM_LINUX_ARM64":    2,
		"PLATFORM_WINDOWS_X86_64": 3,
		"PLATFORM_MACOS_ARM64":    4,
	}
)

func (x Platform) Enum() *Platform {
	p := new(Platform)
	*p = x
	return p
}

func (x Platform) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Platform) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_management_proto_enumTypes[0].Descriptor()
}

func (Platform) Type() protoreflect.EnumType {
	return &file_proto_management_proto_enumTypes[0]
}

func (x Platform) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Platform.Descriptor instead.
func (Platform) EnumDescriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{0}
}

type CreateAlgorithmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Language      string                 `protobuf:"bytes,3,opt,name=language,proto3" json:"language,omitempty"`
	Platform      Platform               `protobuf:"varint,4,opt,name=platform,proto3,enum=api.v1.Platform" json:"platform,omitempty"`
	Entrypoint    string                 `protobuf:"bytes,5,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Tags          []string               `protobuf:"bytes,6,rep,name=tags,proto3" json:"tags,omitempty"`
	PresetDataId  string                 `protobuf:"bytes,7,opt,name=preset_data_id,proto3" json:"preset_data_id,omitempty"`
	FileData      []byte                 `protobuf:"bytes,8,opt,name=file_data,proto3" json:"file_data,omitempty"`
	FileName      string                 `protobuf:"bytes,9,opt,name=file_name,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAlgorithmRequest) Reset() {
	*x = CreateAlgorithmRequest{}
	mi := &file_proto_management_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAlgorithmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAlgorithmRequest) ProtoMessage() {}

func (x *CreateAlgorithmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAlgorithmRequest.ProtoReflect.Descriptor instead.
func (*CreateAlgorithmRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAlgorithmRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAlgorithmRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAlgorithmRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *CreateAlgorithmRequest) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PLATFORM_DOCKER
}

func (x *CreateAlgorithmRequest) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *CreateAlgorithmRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *CreateAlgorithmRequest) GetPresetDataId() string {
	if x != nil {
		return x.PresetDataId
	}
	return ""
}

func (x *CreateAlgorithmRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *CreateAlgorithmRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type UpdateAlgorithmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Tags          []string               `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateAlgorithmRequest) Reset() {
	*x = UpdateAlgorithmRequest{}
	mi := &file_proto_management_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateAlgorithmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAlgorithmRequest) ProtoMessage() {}

func (x *UpdateAlgorithmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAlgorithmRequest.ProtoReflect.Descriptor instead.
func (*UpdateAlgorithmRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateAlgorithmRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateAlgorithmRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateAlgorithmRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateAlgorithmRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type Algorithm struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description      string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Language         string                 `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	Platform         Platform               `protobuf:"varint,5,opt,name=platform,proto3,enum=api.v1.Platform" json:"platform,omitempty"`
	Category         string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	Entrypoint       string                 `protobuf:"bytes,7,opt,name=entrypoint,proto3" json:"entrypoint,omitempty"`
	Tags             []string               `protobuf:"bytes,8,rep,name=tags,proto3" json:"tags,omitempty"`
	PresetDataId     string                 `protobuf:"bytes,9,opt,name=preset_data_id,proto3" json:"preset_data_id,omitempty"`
	CurrentVersionId string                 `protobuf:"bytes,10,opt,name=current_version_id,proto3" json:"current_version_id,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=updated_at,proto3" json:"updated_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Algorithm) Reset() {
	*x = Algorithm{}
	mi := &file_proto_management_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Algorithm) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Algorithm) ProtoMessage() {}

func (x *Algorithm) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Algorithm.ProtoReflect.Descriptor instead.
func (*Algorithm) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{2}
}

func (x *Algorithm) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Algorithm) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Algorithm) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Algorithm) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *Algorithm) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PLATFORM_DOCKER
}

func (x *Algorithm) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Algorithm) GetEntrypoint() string {
	if x != nil {
		return x.Entrypoint
	}
	return ""
}

func (x *Algorithm) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Algorithm) GetPresetDataId() string {
	if x != nil {
		return x.PresetDataId
	}
	return ""
}

func (x *Algorithm) GetCurrentVersionId() string {
	if x != nil {
		return x.CurrentVersionId
	}
	return ""
}

func (x *Algorithm) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Algorithm) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ListAlgorithmsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Language      string                 `protobuf:"bytes,2,opt,name=language,proto3" json:"language,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlgorithmsRequest) Reset() {
	*x = ListAlgorithmsRequest{}
	mi := &file_proto_management_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlgorithmsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlgorithmsRequest) ProtoMessage() {}

func (x *ListAlgorithmsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlgorithmsRequest.ProtoReflect.Descriptor instead.
func (*ListAlgorithmsRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{3}
}

func (x *ListAlgorithmsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListAlgorithmsRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ListAlgorithmsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAlgorithmsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListAlgorithmsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithms    []*Algorithm           `protobuf:"bytes,1,rep,name=algorithms,proto3" json:"algorithms,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAlgorithmsResponse) Reset() {
	*x = ListAlgorithmsResponse{}
	mi := &file_proto_management_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAlgorithmsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAlgorithmsResponse) ProtoMessage() {}

func (x *ListAlgorithmsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAlgorithmsResponse.ProtoReflect.Descriptor instead.
func (*ListAlgorithmsResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{4}
}

func (x *ListAlgorithmsResponse) GetAlgorithms() []*Algorithm {
	if x != nil {
		return x.Algorithms
	}
	return nil
}

func (x *ListAlgorithmsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetAlgorithmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlgorithmRequest) Reset() {
	*x = GetAlgorithmRequest{}
	mi := &file_proto_management_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlgorithmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlgorithmRequest) ProtoMessage() {}

func (x *GetAlgorithmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlgorithmRequest.ProtoReflect.Descriptor instead.
func (*GetAlgorithmRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{5}
}

func (x *GetAlgorithmRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetAlgorithmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algorithm     *Algorithm             `protobuf:"bytes,1,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	Versions      []*Version             `protobuf:"bytes,2,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAlgorithmResponse) Reset() {
	*x = GetAlgorithmResponse{}
	mi := &file_proto_management_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlgorithmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlgorithmResponse) ProtoMessage() {}

func (x *GetAlgorithmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlgorithmResponse.ProtoReflect.Descriptor instead.
func (*GetAlgorithmResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{6}
}

func (x *GetAlgorithmResponse) GetAlgorithm() *Algorithm {
	if x != nil {
		return x.Algorithm
	}
	return nil
}

func (x *GetAlgorithmResponse) GetVersions() []*Version {
	if x != nil {
		return x.Versions
	}
	return nil
}

type CreateVersionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AlgorithmId      string                 `protobuf:"bytes,1,opt,name=algorithm_id,proto3" json:"algorithm_id,omitempty"`
	SourceCodeZipUrl string                 `protobuf:"bytes,2,opt,name=source_code_zip_url,proto3" json:"source_code_zip_url,omitempty"`
	CommitMessage    string                 `protobuf:"bytes,3,opt,name=commit_message,proto3" json:"commit_message,omitempty"`
	FileData         []byte                 `protobuf:"bytes,4,opt,name=file_data,proto3" json:"file_data,omitempty"`
	FileName         string                 `protobuf:"bytes,5,opt,name=file_name,proto3" json:"file_name,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *CreateVersionRequest) Reset() {
	*x = CreateVersionRequest{}
	mi := &file_proto_management_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVersionRequest) ProtoMessage() {}

func (x *CreateVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVersionRequest.ProtoReflect.Descriptor instead.
func (*CreateVersionRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{7}
}

func (x *CreateVersionRequest) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *CreateVersionRequest) GetSourceCodeZipUrl() string {
	if x != nil {
		return x.SourceCodeZipUrl
	}
	return ""
}

func (x *CreateVersionRequest) GetCommitMessage() string {
	if x != nil {
		return x.CommitMessage
	}
	return ""
}

func (x *CreateVersionRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *CreateVersionRequest) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type Version struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AlgorithmId    string                 `protobuf:"bytes,2,opt,name=algorithm_id,proto3" json:"algorithm_id,omitempty"`
	VersionNumber  int32                  `protobuf:"varint,3,opt,name=version_number,proto3" json:"version_number,omitempty"`
	MinioPath      string                 `protobuf:"bytes,4,opt,name=minio_path,proto3" json:"minio_path,omitempty"`
	SourceCodeFile string                 `protobuf:"bytes,5,opt,name=source_code_file,proto3" json:"source_code_file,omitempty"`
	CommitMessage  string                 `protobuf:"bytes,6,opt,name=commit_message,proto3" json:"commit_message,omitempty"`
	CreatedAt      *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=created_at,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Version) Reset() {
	*x = Version{}
	mi := &file_proto_management_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Version) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Version) ProtoMessage() {}

func (x *Version) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Version.ProtoReflect.Descriptor instead.
func (*Version) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{8}
}

func (x *Version) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Version) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *Version) GetVersionNumber() int32 {
	if x != nil {
		return x.VersionNumber
	}
	return 0
}

func (x *Version) GetMinioPath() string {
	if x != nil {
		return x.MinioPath
	}
	return ""
}

func (x *Version) GetSourceCodeFile() string {
	if x != nil {
		return x.SourceCodeFile
	}
	return ""
}

func (x *Version) GetCommitMessage() string {
	if x != nil {
		return x.CommitMessage
	}
	return ""
}

func (x *Version) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type RollbackVersionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlgorithmId   string                 `protobuf:"bytes,1,opt,name=algorithm_id,proto3" json:"algorithm_id,omitempty"`
	VersionId     string                 `protobuf:"bytes,2,opt,name=version_id,proto3" json:"version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RollbackVersionRequest) Reset() {
	*x = RollbackVersionRequest{}
	mi := &file_proto_management_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RollbackVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RollbackVersionRequest) ProtoMessage() {}

func (x *RollbackVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RollbackVersionRequest.ProtoReflect.Descriptor instead.
func (*RollbackVersionRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{9}
}

func (x *RollbackVersionRequest) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *RollbackVersionRequest) GetVersionId() string {
	if x != nil {
		return x.VersionId
	}
	return ""
}

type UploadDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filename      string                 `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Category      string                 `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	FileData      []byte                 `protobuf:"bytes,3,opt,name=file_data,proto3" json:"file_data,omitempty"`
	MinioPath     string                 `protobuf:"bytes,4,opt,name=minio_path,proto3" json:"minio_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDataRequest) Reset() {
	*x = UploadDataRequest{}
	mi := &file_proto_management_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDataRequest) ProtoMessage() {}

func (x *UploadDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDataRequest.ProtoReflect.Descriptor instead.
func (*UploadDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{10}
}

func (x *UploadDataRequest) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *UploadDataRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UploadDataRequest) GetFileData() []byte {
	if x != nil {
		return x.FileData
	}
	return nil
}

func (x *UploadDataRequest) GetMinioPath() string {
	if x != nil {
		return x.MinioPath
	}
	return ""
}

type UploadDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileId        string                 `protobuf:"bytes,1,opt,name=file_id,proto3" json:"file_id,omitempty"`
	MinioUrl      string                 `protobuf:"bytes,2,opt,name=minio_url,proto3" json:"minio_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadDataResponse) Reset() {
	*x = UploadDataResponse{}
	mi := &file_proto_management_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadDataResponse) ProtoMessage() {}

func (x *UploadDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadDataResponse.ProtoReflect.Descriptor instead.
func (*UploadDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{11}
}

func (x *UploadDataResponse) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *UploadDataResponse) GetMinioUrl() string {
	if x != nil {
		return x.MinioUrl
	}
	return ""
}

type ListPresetDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPresetDataRequest) Reset() {
	*x = ListPresetDataRequest{}
	mi := &file_proto_management_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPresetDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPresetDataRequest) ProtoMessage() {}

func (x *ListPresetDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPresetDataRequest.ProtoReflect.Descriptor instead.
func (*ListPresetDataRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{12}
}

func (x *ListPresetDataRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListPresetDataRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListPresetDataRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type PresetData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filename      string                 `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	MinioUrl      string                 `protobuf:"bytes,4,opt,name=minio_url,proto3" json:"minio_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresetData) Reset() {
	*x = PresetData{}
	mi := &file_proto_management_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresetData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresetData) ProtoMessage() {}

func (x *PresetData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresetData.ProtoReflect.Descriptor instead.
func (*PresetData) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{13}
}

func (x *PresetData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PresetData) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

func (x *PresetData) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *PresetData) GetMinioUrl() string {
	if x != nil {
		return x.MinioUrl
	}
	return ""
}

func (x *PresetData) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListPresetDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Files         []*PresetData          `protobuf:"bytes,1,rep,name=files,proto3" json:"files,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPresetDataResponse) Reset() {
	*x = ListPresetDataResponse{}
	mi := &file_proto_management_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPresetDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPresetDataResponse) ProtoMessage() {}

func (x *ListPresetDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPresetDataResponse.ProtoReflect.Descriptor instead.
func (*ListPresetDataResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{14}
}

func (x *ListPresetDataResponse) GetFiles() []*PresetData {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ListPresetDataResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type ListJobsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AlgorithmId   string                 `protobuf:"bytes,1,opt,name=algorithm_id,proto3" json:"algorithm_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,4,opt,name=page_size,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsRequest) Reset() {
	*x = ListJobsRequest{}
	mi := &file_proto_management_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsRequest) ProtoMessage() {}

func (x *ListJobsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsRequest.ProtoReflect.Descriptor instead.
func (*ListJobsRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{15}
}

func (x *ListJobsRequest) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *ListJobsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListJobsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListJobsRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type JobSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,proto3" json:"job_id,omitempty"`
	AlgorithmId   string                 `protobuf:"bytes,2,opt,name=algorithm_id,proto3" json:"algorithm_id,omitempty"`
	AlgorithmName string                 `protobuf:"bytes,3,opt,name=algorithm_name,proto3" json:"algorithm_name,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,proto3" json:"created_at,omitempty"`
	CostTimeMs    int32                  `protobuf:"varint,6,opt,name=cost_time_ms,proto3" json:"cost_time_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobSummary) Reset() {
	*x = JobSummary{}
	mi := &file_proto_management_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobSummary) ProtoMessage() {}

func (x *JobSummary) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobSummary.ProtoReflect.Descriptor instead.
func (*JobSummary) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{16}
}

func (x *JobSummary) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobSummary) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *JobSummary) GetAlgorithmName() string {
	if x != nil {
		return x.AlgorithmName
	}
	return ""
}

func (x *JobSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobSummary) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *JobSummary) GetCostTimeMs() int32 {
	if x != nil {
		return x.CostTimeMs
	}
	return 0
}

type ListJobsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jobs          []*JobSummary          `protobuf:"bytes,1,rep,name=jobs,proto3" json:"jobs,omitempty"`
	Total         int32                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListJobsResponse) Reset() {
	*x = ListJobsResponse{}
	mi := &file_proto_management_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListJobsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListJobsResponse) ProtoMessage() {}

func (x *ListJobsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListJobsResponse.ProtoReflect.Descriptor instead.
func (*ListJobsResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{17}
}

func (x *ListJobsResponse) GetJobs() []*JobSummary {
	if x != nil {
		return x.Jobs
	}
	return nil
}

func (x *ListJobsResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetJobDetailRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,proto3" json:"job_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetJobDetailRequest) Reset() {
	*x = GetJobDetailRequest{}
	mi := &file_proto_management_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetJobDetailRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJobDetailRequest) ProtoMessage() {}

func (x *GetJobDetailRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJobDetailRequest.ProtoReflect.Descriptor instead.
func (*GetJobDetailRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{18}
}

func (x *GetJobDetailRequest) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type JobDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobId         string                 `protobuf:"bytes,1,opt,name=job_id,proto3" json:"job_id,omitempty"`
	AlgorithmId   string                 `protobuf:"bytes,2,opt,name=algorithm_id,proto3" json:"algorithm_id,omitempty"`
	AlgorithmName string                 `protobuf:"bytes,3,opt,name=algorithm_name,proto3" json:"algorithm_name,omitempty"`
	Mode          string                 `protobuf:"bytes,4,opt,name=mode,proto3" json:"mode,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	InputParams   string                 `protobuf:"bytes,6,opt,name=input_params,proto3" json:"input_params,omitempty"`
	InputUrl      string                 `protobuf:"bytes,7,opt,name=input_url,proto3" json:"input_url,omitempty"`
	OutputUrl     string                 `protobuf:"bytes,8,opt,name=output_url,proto3" json:"output_url,omitempty"`
	LogUrl        string                 `protobuf:"bytes,9,opt,name=log_url,proto3" json:"log_url,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,proto3" json:"created_at,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=started_at,proto3" json:"started_at,omitempty"`
	FinishedAt    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=finished_at,proto3" json:"finished_at,omitempty"`
	CostTimeMs    int32                  `protobuf:"varint,13,opt,name=cost_time_ms,proto3" json:"cost_time_ms,omitempty"`
	WorkerId      string                 `protobuf:"bytes,14,opt,name=worker_id,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JobDetail) Reset() {
	*x = JobDetail{}
	mi := &file_proto_management_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JobDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JobDetail) ProtoMessage() {}

func (x *JobDetail) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JobDetail.ProtoReflect.Descriptor instead.
func (*JobDetail) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{19}
}

func (x *JobDetail) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *JobDetail) GetAlgorithmId() string {
	if x != nil {
		return x.AlgorithmId
	}
	return ""
}

func (x *JobDetail) GetAlgorithmName() string {
	if x != nil {
		return x.AlgorithmName
	}
	return ""
}

func (x *JobDetail) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *JobDetail) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *JobDetail) GetInputParams() string {
	if x != nil {
		return x.InputParams
	}
	return ""
}

func (x *JobDetail) GetInputUrl() string {
	if x != nil {
		return x.InputUrl
	}
	return ""
}

func (x *JobDetail) GetOutputUrl() string {
	if x != nil {
		return x.OutputUrl
	}
	return ""
}

func (x *JobDetail) GetLogUrl() string {
	if x != nil {
		return x.LogUrl
	}
	return ""
}

func (x *JobDetail) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *JobDetail) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *JobDetail) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

func (x *JobDetail) GetCostTimeMs() int32 {
	if x != nil {
		return x.CostTimeMs
	}
	return 0
}

func (x *JobDetail) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

type GetServerInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerInfoRequest) Reset() {
	*x = GetServerInfoRequest{}
	mi := &file_proto_management_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoRequest) ProtoMessage() {}

func (x *GetServerInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoRequest.ProtoReflect.Descriptor instead.
func (*GetServerInfoRequest) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{20}
}

type GetServerInfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Platform      Platform               `protobuf:"varint,3,opt,name=platform,proto3,enum=api.v1.Platform" json:"platform,omitempty"`
	PlatformName  string                 `protobuf:"bytes,4,opt,name=platform_name,proto3" json:"platform_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetServerInfoResponse) Reset() {
	*x = GetServerInfoResponse{}
	mi := &file_proto_management_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetServerInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetServerInfoResponse) ProtoMessage() {}

func (x *GetServerInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_management_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetServerInfoResponse.ProtoReflect.Descriptor instead.
func (*GetServerInfoResponse) Descriptor() ([]byte, []int) {
	return file_proto_management_proto_rawDescGZIP(), []int{21}
}

func (x *GetServerInfoResponse) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *GetServerInfoResponse) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *GetServerInfoResponse) GetPlatform() Platform {
	if x != nil {
		return x.Platform
	}
	return Platform_PLATFORM_DOCKER
}

func (x *GetServerInfoResponse) GetPlatformName() string {
	if x != nil {
		return x.PlatformName
	}
	return ""
}

var File_proto_management_proto protoreflect.FileDescriptor

const file_proto_management_proto_rawDesc = "" +
	"\n" +
	"\x16proto/management.proto\x12\x06api.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb0\x02\n" +
	"\x16CreateAlgorithmRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\blanguage\x18\x03 \x01(\tR\blanguage\x12,\n" +
	"\bplatform\x18\x04 \x01(\x0e2\x10.api.v1.PlatformR\bplatform\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\x05 \x01(\tR\n" +
	"entrypoint\x12\x12\n" +
	"\x04tags\x18\x06 \x03(\tR\x04tags\x12&\n" +
	"\x0epreset_data_id\x18\a \x01(\tR\x0epreset_data_id\x12\x1c\n" +
	"\tfile_data\x18\b \x01(\fR\tfile_data\x12\x1c\n" +
	"\tfile_name\x18\t \x01(\tR\tfile_name\"r\n" +
	"\x16UpdateAlgorithmRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x12\n" +
	"\x04tags\x18\x04 \x03(\tR\x04tags\"\xbb\x03\n" +
	"\tAlgorithm\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\blanguage\x18\x04 \x01(\tR\blanguage\x12,\n" +
	"\bplatform\x18\x05 \x01(\x0e2\x10.api.v1.PlatformR\bplatform\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x1e\n" +
	"\n" +
	"entrypoint\x18\a \x01(\tR\n" +
	"entrypoint\x12\x12\n" +
	"\x04tags\x18\b \x03(\tR\x04tags\x12&\n" +
	"\x0epreset_data_id\x18\t \x01(\tR\x0epreset_data_id\x12.\n" +
	"\x12current_version_id\x18\n" +
	" \x01(\tR\x12current_version_id\x12:\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_at\x12:\n" +
	"\n" +
	"updated_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updated_at\"\x81\x01\n" +
	"\x15ListAlgorithmsRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x1a\n" +
	"\blanguage\x18\x02 \x01(\tR\blanguage\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1c\n" +
	"\tpage_size\x18\x04 \x01(\x05R\tpage_size\"a\n" +
	"\x16ListAlgorithmsResponse\x121\n" +
	"\n" +
	"algorithms\x18\x01 \x03(\v2\x11.api.v1.AlgorithmR\n" +
	"algorithms\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"%\n" +
	"\x13GetAlgorithmRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"t\n" +
	"\x14GetAlgorithmResponse\x12/\n" +
	"\talgorithm\x18\x01 \x01(\v2\x11.api.v1.AlgorithmR\talgorithm\x12+\n" +
	"\bversions\x18\x02 \x03(\v2\x0f.api.v1.VersionR\bversions\"\xd0\x01\n" +
	"\x14CreateVersionRequest\x12\"\n" +
	"\falgorithm_id\x18\x01 \x01(\tR\falgorithm_id\x120\n" +
	"\x13source_code_zip_url\x18\x02 \x01(\tR\x13source_code_zip_url\x12&\n" +
	"\x0ecommit_message\x18\x03 \x01(\tR\x0ecommit_message\x12\x1c\n" +
	"\tfile_data\x18\x04 \x01(\fR\tfile_data\x12\x1c\n" +
	"\tfile_name\x18\x05 \x01(\tR\tfile_name\"\x95\x02\n" +
	"\aVersion\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\falgorithm_id\x18\x02 \x01(\tR\falgorithm_id\x12&\n" +
	"\x0eversion_number\x18\x03 \x01(\x05R\x0eversion_number\x12\x1e\n" +
	"\n" +
	"minio_path\x18\x04 \x01(\tR\n" +
	"minio_path\x12*\n" +
	"\x10source_code_file\x18\x05 \x01(\tR\x10source_code_file\x12&\n" +
	"\x0ecommit_message\x18\x06 \x01(\tR\x0ecommit_message\x12:\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_at\"\\\n" +
	"\x16RollbackVersionRequest\x12\"\n" +
	"\falgorithm_id\x18\x01 \x01(\tR\falgorithm_id\x12\x1e\n" +
	"\n" +
	"version_id\x18\x02 \x01(\tR\n" +
	"version_id\"\x89\x01\n" +
	"\x11UploadDataRequest\x12\x1a\n" +
	"\bfilename\x18\x01 \x01(\tR\bfilename\x12\x1a\n" +
	"\bcategory\x18\x02 \x01(\tR\bcategory\x12\x1c\n" +
	"\tfile_data\x18\x03 \x01(\fR\tfile_data\x12\x1e\n" +
	"\n" +
	"minio_path\x18\x04 \x01(\tR\n" +
	"minio_path\"L\n" +
	"\x12UploadDataResponse\x12\x18\n" +
	"\afile_id\x18\x01 \x01(\tR\afile_id\x12\x1c\n" +
	"\tminio_url\x18\x02 \x01(\tR\tminio_url\"e\n" +
	"\x15ListPresetDataRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1c\n" +
	"\tpage_size\x18\x03 \x01(\x05R\tpage_size\"\xae\x01\n" +
	"\n" +
	"PresetData\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bfilename\x18\x02 \x01(\tR\bfilename\x12\x1a\n" +
	"\bcategory\x18\x03 \x01(\tR\bcategory\x12\x1c\n" +
	"\tminio_url\x18\x04 \x01(\tR\tminio_url\x12:\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_at\"X\n" +
	"\x16ListPresetDataResponse\x12(\n" +
	"\x05files\x18\x01 \x03(\v2\x12.api.v1.PresetDataR\x05files\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"\x7f\n" +
	"\x0fListJobsRequest\x12\"\n" +
	"\falgorithm_id\x18\x01 \x01(\tR\falgorithm_id\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x1c\n" +
	"\tpage_size\x18\x04 \x01(\x05R\tpage_size\"\xe8\x01\n" +
	"\n" +
	"JobSummary\x12\x16\n" +
	"\x06job_id\x18\x01 \x01(\tR\x06job_id\x12\"\n" +
	"\falgorithm_id\x18\x02 \x01(\tR\falgorithm_id\x12&\n" +
	"\x0ealgorithm_name\x18\x03 \x01(\tR\x0ealgorithm_name\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12:\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_at\x12\"\n" +
	"\fcost_time_ms\x18\x06 \x01(\x05R\fcost_time_ms\"P\n" +
	"\x10ListJobsResponse\x12&\n" +
	"\x04jobs\x18\x01 \x03(\v2\x12.api.v1.JobSummaryR\x04jobs\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x05R\x05total\"-\n" +
	"\x13GetJobDetailRequest\x12\x16\n" +
	"\x06job_id\x18\x01 \x01(\tR\x06job_id\"\x8f\x04\n" +
	"\tJobDetail\x12\x16\n" +
	"\x06job_id\x18\x01 \x01(\tR\x06job_id\x12\"\n" +
	"\falgorithm_id\x18\x02 \x01(\tR\falgorithm_id\x12&\n" +
	"\x0ealgorithm_name\x18\x03 \x01(\tR\x0ealgorithm_name\x12\x12\n" +
	"\x04mode\x18\x04 \x01(\tR\x04mode\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\"\n" +
	"\finput_params\x18\x06 \x01(\tR\finput_params\x12\x1c\n" +
	"\tinput_url\x18\a \x01(\tR\tinput_url\x12\x1e\n" +
	"\n" +
	"output_url\x18\b \x01(\tR\n" +
	"output_url\x12\x18\n" +
	"\alog_url\x18\t \x01(\tR\alog_url\x12:\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"created_at\x12:\n" +
	"\n" +
	"started_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"started_at\x12<\n" +
	"\vfinished_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\vfinished_at\x12\"\n" +
	"\fcost_time_ms\x18\r \x01(\x05R\fcost_time_ms\x12\x1c\n" +
	"\tworker_id\x18\x0e \x01(\tR\tworker_id\"\x16\n" +
	"\x14GetServerInfoRequest\"\x8f\x01\n" +
	"\x15GetServerInfoResponse\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12,\n" +
	"\bplatform\x18\x03 \x01(\x0e2\x10.api.v1.PlatformR\bplatform\x12$\n" +
	"\rplatform_name\x18\x04 \x01(\tR\rplatform_name*\x8b\x01\n" +
	"\bPlatform\x12\x13\n" +
	"\x0fPLATFORM_DOCKER\x10\x00\x12\x19\n" +
	"\x15PLATFORM_LINUX_X86_64\x10\x01\x12\x18\n" +
	"\x14PLATFORM_LINUX_ARM64\x10\x02\x12\x1b\n" +
	"\x17PLATFORM_WINDOWS_X86_64\x10\x03\x12\x18\n" +
	"\x14PLATFORM_MACOS_ARM64\x10\x042\xbe\t\n" +
	"\x11ManagementService\x12c\n" +
	"\x0fCreateAlgorithm\x12\x1e.api.v1.CreateAlgorithmRequest\x1a\x11.api.v1.Algorithm\"\x1d\x82\xd3\xe4\x93\x02\x17:\x01*\"\x12/api/v1/algorithms\x12h\n" +
	"\x0fUpdateAlgorithm\x12\x1e.api.v1.UpdateAlgorithmRequest\x1a\x11.api.v1.Algorithm\"\"\x82\xd3\xe4\x93\x02\x1c:\x01*\x1a\x17/api/v1/algorithms/{id}\x12k\n" +
	"\x0eListAlgorithms\x12\x1d.api.v1.ListAlgorithmsRequest\x1a\x1e.api.v1.ListAlgorithmsResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/api/v1/algorithms\x12j\n" +
	"\fGetAlgorithm\x12\x1b.api.v1.GetAlgorithmRequest\x1a\x1c.api.v1.GetAlgorithmResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\x12\x17/api/v1/algorithms/{id}\x12u\n" +
	"\rCreateVersion\x12\x1c.api.v1.CreateVersionRequest\x1a\x0f.api.v1.Version\"5\x82\xd3\xe4\x93\x02/:\x01*\"*/api/v1/algorithms/{algorithm_id}/versions\x12\x91\x01\n" +
	"\x0fRollbackVersion\x12\x1e.api.v1.RollbackVersionRequest\x1a\x11.api.v1.Algorithm\"K\x82\xd3\xe4\x93\x02E:\x01*\"@/api/v1/algorithms/{algorithm_id}/versions/{version_id}/rollback\x12i\n" +
	"\x10UploadPresetData\x12\x19.api.v1.UploadDataRequest\x1a\x1a.api.v1.UploadDataResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/api/v1/data/upload\x12e\n" +
	"\x0eListPresetData\x12\x1d.api.v1.ListPresetDataRequest\x1a\x1e.api.v1.ListPresetDataResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/data\x12S\n" +
	"\bListJobs\x12\x17.api.v1.ListJobsRequest\x1a\x18.api.v1.ListJobsResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/api/v1/jobs\x12d\n" +
	"\fGetJobDetail\x12\x1b.api.v1.GetJobDetailRequest\x1a\x11.api.v1.JobDetail\"$\x82\xd3\xe4\x93\x02\x1e\x12\x1c/api/v1/jobs/{job_id}/detail\x12i\n" +
	"\rGetServerInfo\x12\x1c.api.v1.GetServerInfoRequest\x1a\x1d.api.v1.GetServerInfoResponse\"\x1b\x82\xd3\xe4\x93\x02\x15\x12\x13/api/v1/server/infoB$Z\"algorithm-platform/api/v1/proto;v1b\x06proto3"

var (
	file_proto_management_proto_rawDescOnce sync.Once
	file_proto_management_proto_rawDescData []byte
)

func file_proto_management_proto_rawDescGZIP() []byte {
	file_proto_management_proto_rawDescOnce.Do(func() {
		file_proto_management_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_management_proto_rawDesc), len(file_proto_management_proto_rawDesc)))
	})
	return file_proto_management_proto_rawDescData
}

var file_proto_management_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_management_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_proto_management_proto_goTypes = []any{
	(Platform)(0),                  // 0: api.v1.Platform
	(*CreateAlgorithmRequest)(nil), // 1: api.v1.CreateAlgorithmRequest
	(*UpdateAlgorithmRequest)(nil), // 2: api.v1.UpdateAlgorithmRequest
	(*Algorithm)(nil),              // 3: api.v1.Algorithm
	(*ListAlgorithmsRequest)(nil),  // 4: api.v1.ListAlgorithmsRequest
	(*ListAlgorithmsResponse)(nil), // 5: api.v1.ListAlgorithmsResponse
	(*GetAlgorithmRequest)(nil),    // 6: api.v1.GetAlgorithmRequest
	(*GetAlgorithmResponse)(nil),   // 7: api.v1.GetAlgorithmResponse
	(*CreateVersionRequest)(nil),   // 8: api.v1.CreateVersionRequest
	(*Version)(nil),                // 9: api.v1.Version
	(*RollbackVersionRequest)(nil), // 10: api.v1.RollbackVersionRequest
	(*UploadDataRequest)(nil),      // 11: api.v1.UploadDataRequest
	(*UploadDataResponse)(nil),     // 12: api.v1.UploadDataResponse
	(*ListPresetDataRequest)(nil),  // 13: api.v1.ListPresetDataRequest
	(*PresetData)(nil),             // 14: api.v1.PresetData
	(*ListPresetDataResponse)(nil), // 15: api.v1.ListPresetDataResponse
	(*ListJobsRequest)(nil),        // 16: api.v1.ListJobsRequest
	(*JobSummary)(nil),             // 17: api.v1.JobSummary
	(*ListJobsResponse)(nil),       // 18: api.v1.ListJobsResponse
	(*GetJobDetailRequest)(nil),    // 19: api.v1.GetJobDetailRequest
	(*JobDetail)(nil),              // 20: api.v1.JobDetail
	(*GetServerInfoRequest)(nil),   // 21: api.v1.GetServerInfoRequest
	(*GetServerInfoResponse)(nil),  // 22: api.v1.GetServerInfoResponse
	(*timestamppb.Timestamp)(nil),  // 23: google.protobuf.Timestamp
}
var file_proto_management_proto_depIdxs = []int32{
	0,  // 0: api.v1.CreateAlgorithmRequest.platform:type_name -> api.v1.Platform
	0,  // 1: api.v1.Algorithm.platform:type_name -> api.v1.Platform
	23, // 2: api.v1.Algorithm.created_at:type_name -> google.protobuf.Timestamp
	23, // 3: api.v1.Algorithm.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 4: api.v1.ListAlgorithmsResponse.algorithms:type_name -> api.v1.Algorithm
	3,  // 5: api.v1.GetAlgorithmResponse.algorithm:type_name -> api.v1.Algorithm
	9,  // 6: api.v1.GetAlgorithmResponse.versions:type_name -> api.v1.Version
	23, // 7: api.v1.Version.created_at:type_name -> google.protobuf.Timestamp
	23, // 8: api.v1.PresetData.created_at:type_name -> google.protobuf.Timestamp
	14, // 9: api.v1.ListPresetDataResponse.files:type_name -> api.v1.PresetData
	23, // 10: api.v1.JobSummary.created_at:type_name -> google.protobuf.Timestamp
	17, // 11: api.v1.ListJobsResponse.jobs:type_name -> api.v1.JobSummary
	23, // 12: api.v1.JobDetail.created_at:type_name -> google.protobuf.Timestamp
	23, // 13: api.v1.JobDetail.started_at:type_name -> google.protobuf.Timestamp
	23, // 14: api.v1.JobDetail.finished_at:type_name -> google.protobuf.Timestamp
	0,  // 15: api.v1.GetServerInfoResponse.platform:type_name -> api.v1.Platform
	1,  // 16: api.v1.ManagementService.CreateAlgorithm:input_type -> api.v1.CreateAlgorithmRequest
	2,  // 17: api.v1.ManagementService.UpdateAlgorithm:input_type -> api.v1.UpdateAlgorithmRequest
	4,  // 18: api.v1.ManagementService.ListAlgorithms:input_type -> api.v1.ListAlgorithmsRequest
	6,  // 19: api.v1.ManagementService.GetAlgorithm:input_type -> api.v1.GetAlgorithmRequest
	8,  // 20: api.v1.ManagementService.CreateVersion:input_type -> api.v1.CreateVersionRequest
	10, // 21: api.v1.ManagementService.RollbackVersion:input_type -> api.v1.RollbackVersionRequest
	11, // 22: api.v1.ManagementService.UploadPresetData:input_type -> api.v1.UploadDataRequest
	13, // 23: api.v1.ManagementService.ListPresetData:input_type -> api.v1.ListPresetDataRequest
	16, // 24: api.v1.ManagementService.ListJobs:input_type -> api.v1.ListJobsRequest
	19, // 25: api.v1.ManagementService.GetJobDetail:input_type -> api.v1.GetJobDetailRequest
	21, // 26: api.v1.ManagementService.GetServerInfo:input_type -> api.v1.GetServerInfoRequest
	3,  // 27: api.v1.ManagementService.CreateAlgorithm:output_type -> api.v1.Algorithm
	3,  // 28: api.v1.ManagementService.UpdateAlgorithm:output_type -> api.v1.Algorithm
	5,  // 29: api.v1.ManagementService.ListAlgorithms:output_type -> api.v1.ListAlgorithmsResponse
	7,  // 30: api.v1.ManagementService.GetAlgorithm:output_type -> api.v1.GetAlgorithmResponse
	9,  // 31: api.v1.ManagementService.CreateVersion:output_type -> api.v1.Version
	3,  // 32: api.v1.ManagementService.RollbackVersion:output_type -> api.v1.Algorithm
	12, // 33: api.v1.ManagementService.UploadPresetData:output_type -> api.v1.UploadDataResponse
	15, // 34: api.v1.ManagementService.ListPresetData:output_type -> api.v1.ListPresetDataResponse
	18, // 35: api.v1.ManagementService.ListJobs:output_type -> api.v1.ListJobsResponse
	20, // 36: api.v1.ManagementService.GetJobDetail:output_type -> api.v1.JobDetail
	22, // 37: api.v1.ManagementService.GetServerInfo:output_type -> api.v1.GetServerInfoResponse
	27, // [27:38] is the sub-list for method output_type
	16, // [16:27] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_proto_management_proto_init() }
func file_proto_management_proto_init() {
	if File_proto_management_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_management_proto_rawDesc), len(file_proto_management_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_management_proto_goTypes,
		DependencyIndexes: file_proto_management_proto_depIdxs,
		EnumInfos:         file_proto_management_proto_enumTypes,
		MessageInfos:      file_proto_management_proto_msgTypes,
	}.Build()
	File_proto_management_proto = out.File
	file_proto_management_proto_goTypes = nil
	file_proto_management_proto_depIdxs = nil
}
