// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             (unknown)
// source: proto/management.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ManagementService_CreateAlgorithm_FullMethodName  = "/api.v1.ManagementService/CreateAlgorithm"
	ManagementService_UpdateAlgorithm_FullMethodName  = "/api.v1.ManagementService/UpdateAlgorithm"
	ManagementService_ListAlgorithms_FullMethodName   = "/api.v1.ManagementService/ListAlgorithms"
	ManagementService_GetAlgorithm_FullMethodName     = "/api.v1.ManagementService/GetAlgorithm"
	ManagementService_CreateVersion_FullMethodName    = "/api.v1.ManagementService/CreateVersion"
	ManagementService_RollbackVersion_FullMethodName  = "/api.v1.ManagementService/RollbackVersion"
	ManagementService_UploadPresetData_FullMethodName = "/api.v1.ManagementService/UploadPresetData"
	ManagementService_ListPresetData_FullMethodName   = "/api.v1.ManagementService/ListPresetData"
	ManagementService_DeletePresetData_FullMethodName = "/api.v1.ManagementService/DeletePresetData"
	ManagementService_ListJobs_FullMethodName         = "/api.v1.ManagementService/ListJobs"
	ManagementService_GetJobDetail_FullMethodName     = "/api.v1.ManagementService/GetJobDetail"
	ManagementService_GetServerInfo_FullMethodName    = "/api.v1.ManagementService/GetServerInfo"
)

// ManagementServiceClient is the client API for ManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ManagementServiceClient interface {
	CreateAlgorithm(ctx context.Context, in *CreateAlgorithmRequest, opts ...grpc.CallOption) (*Algorithm, error)
	UpdateAlgorithm(ctx context.Context, in *UpdateAlgorithmRequest, opts ...grpc.CallOption) (*Algorithm, error)
	ListAlgorithms(ctx context.Context, in *ListAlgorithmsRequest, opts ...grpc.CallOption) (*ListAlgorithmsResponse, error)
	GetAlgorithm(ctx context.Context, in *GetAlgorithmRequest, opts ...grpc.CallOption) (*GetAlgorithmResponse, error)
	CreateVersion(ctx context.Context, in *CreateVersionRequest, opts ...grpc.CallOption) (*Version, error)
	RollbackVersion(ctx context.Context, in *RollbackVersionRequest, opts ...grpc.CallOption) (*Algorithm, error)
	UploadPresetData(ctx context.Context, in *UploadDataRequest, opts ...grpc.CallOption) (*UploadDataResponse, error)
	ListPresetData(ctx context.Context, in *ListPresetDataRequest, opts ...grpc.CallOption) (*ListPresetDataResponse, error)
	DeletePresetData(ctx context.Context, in *DeletePresetDataRequest, opts ...grpc.CallOption) (*DeletePresetDataResponse, error)
	ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error)
	GetJobDetail(ctx context.Context, in *GetJobDetailRequest, opts ...grpc.CallOption) (*JobDetail, error)
	GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*GetServerInfoResponse, error)
}

type managementServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewManagementServiceClient(cc grpc.ClientConnInterface) ManagementServiceClient {
	return &managementServiceClient{cc}
}

func (c *managementServiceClient) CreateAlgorithm(ctx context.Context, in *CreateAlgorithmRequest, opts ...grpc.CallOption) (*Algorithm, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Algorithm)
	err := c.cc.Invoke(ctx, ManagementService_CreateAlgorithm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) UpdateAlgorithm(ctx context.Context, in *UpdateAlgorithmRequest, opts ...grpc.CallOption) (*Algorithm, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Algorithm)
	err := c.cc.Invoke(ctx, ManagementService_UpdateAlgorithm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ListAlgorithms(ctx context.Context, in *ListAlgorithmsRequest, opts ...grpc.CallOption) (*ListAlgorithmsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAlgorithmsResponse)
	err := c.cc.Invoke(ctx, ManagementService_ListAlgorithms_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetAlgorithm(ctx context.Context, in *GetAlgorithmRequest, opts ...grpc.CallOption) (*GetAlgorithmResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAlgorithmResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetAlgorithm_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) CreateVersion(ctx context.Context, in *CreateVersionRequest, opts ...grpc.CallOption) (*Version, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Version)
	err := c.cc.Invoke(ctx, ManagementService_CreateVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) RollbackVersion(ctx context.Context, in *RollbackVersionRequest, opts ...grpc.CallOption) (*Algorithm, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Algorithm)
	err := c.cc.Invoke(ctx, ManagementService_RollbackVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) UploadPresetData(ctx context.Context, in *UploadDataRequest, opts ...grpc.CallOption) (*UploadDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadDataResponse)
	err := c.cc.Invoke(ctx, ManagementService_UploadPresetData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ListPresetData(ctx context.Context, in *ListPresetDataRequest, opts ...grpc.CallOption) (*ListPresetDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPresetDataResponse)
	err := c.cc.Invoke(ctx, ManagementService_ListPresetData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) DeletePresetData(ctx context.Context, in *DeletePresetDataRequest, opts ...grpc.CallOption) (*DeletePresetDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePresetDataResponse)
	err := c.cc.Invoke(ctx, ManagementService_DeletePresetData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) ListJobs(ctx context.Context, in *ListJobsRequest, opts ...grpc.CallOption) (*ListJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListJobsResponse)
	err := c.cc.Invoke(ctx, ManagementService_ListJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetJobDetail(ctx context.Context, in *GetJobDetailRequest, opts ...grpc.CallOption) (*JobDetail, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JobDetail)
	err := c.cc.Invoke(ctx, ManagementService_GetJobDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *managementServiceClient) GetServerInfo(ctx context.Context, in *GetServerInfoRequest, opts ...grpc.CallOption) (*GetServerInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServerInfoResponse)
	err := c.cc.Invoke(ctx, ManagementService_GetServerInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ManagementServiceServer is the server API for ManagementService service.
// All implementations must embed UnimplementedManagementServiceServer
// for forward compatibility.
type ManagementServiceServer interface {
	CreateAlgorithm(context.Context, *CreateAlgorithmRequest) (*Algorithm, error)
	UpdateAlgorithm(context.Context, *UpdateAlgorithmRequest) (*Algorithm, error)
	ListAlgorithms(context.Context, *ListAlgorithmsRequest) (*ListAlgorithmsResponse, error)
	GetAlgorithm(context.Context, *GetAlgorithmRequest) (*GetAlgorithmResponse, error)
	CreateVersion(context.Context, *CreateVersionRequest) (*Version, error)
	RollbackVersion(context.Context, *RollbackVersionRequest) (*Algorithm, error)
	UploadPresetData(context.Context, *UploadDataRequest) (*UploadDataResponse, error)
	ListPresetData(context.Context, *ListPresetDataRequest) (*ListPresetDataResponse, error)
	DeletePresetData(context.Context, *DeletePresetDataRequest) (*DeletePresetDataResponse, error)
	ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error)
	GetJobDetail(context.Context, *GetJobDetailRequest) (*JobDetail, error)
	GetServerInfo(context.Context, *GetServerInfoRequest) (*GetServerInfoResponse, error)
	mustEmbedUnimplementedManagementServiceServer()
}

// UnimplementedManagementServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedManagementServiceServer struct{}

func (UnimplementedManagementServiceServer) CreateAlgorithm(context.Context, *CreateAlgorithmRequest) (*Algorithm, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAlgorithm not implemented")
}
func (UnimplementedManagementServiceServer) UpdateAlgorithm(context.Context, *UpdateAlgorithmRequest) (*Algorithm, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateAlgorithm not implemented")
}
func (UnimplementedManagementServiceServer) ListAlgorithms(context.Context, *ListAlgorithmsRequest) (*ListAlgorithmsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAlgorithms not implemented")
}
func (UnimplementedManagementServiceServer) GetAlgorithm(context.Context, *GetAlgorithmRequest) (*GetAlgorithmResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAlgorithm not implemented")
}
func (UnimplementedManagementServiceServer) CreateVersion(context.Context, *CreateVersionRequest) (*Version, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateVersion not implemented")
}
func (UnimplementedManagementServiceServer) RollbackVersion(context.Context, *RollbackVersionRequest) (*Algorithm, error) {
	return nil, status.Error(codes.Unimplemented, "method RollbackVersion not implemented")
}
func (UnimplementedManagementServiceServer) UploadPresetData(context.Context, *UploadDataRequest) (*UploadDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UploadPresetData not implemented")
}
func (UnimplementedManagementServiceServer) ListPresetData(context.Context, *ListPresetDataRequest) (*ListPresetDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPresetData not implemented")
}
func (UnimplementedManagementServiceServer) DeletePresetData(context.Context, *DeletePresetDataRequest) (*DeletePresetDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeletePresetData not implemented")
}
func (UnimplementedManagementServiceServer) ListJobs(context.Context, *ListJobsRequest) (*ListJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListJobs not implemented")
}
func (UnimplementedManagementServiceServer) GetJobDetail(context.Context, *GetJobDetailRequest) (*JobDetail, error) {
	return nil, status.Error(codes.Unimplemented, "method GetJobDetail not implemented")
}
func (UnimplementedManagementServiceServer) GetServerInfo(context.Context, *GetServerInfoRequest) (*GetServerInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServerInfo not implemented")
}
func (UnimplementedManagementServiceServer) mustEmbedUnimplementedManagementServiceServer() {}
func (UnimplementedManagementServiceServer) testEmbeddedByValue()                           {}

// UnsafeManagementServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ManagementServiceServer will
// result in compilation errors.
type UnsafeManagementServiceServer interface {
	mustEmbedUnimplementedManagementServiceServer()
}

func RegisterManagementServiceServer(s grpc.ServiceRegistrar, srv ManagementServiceServer) {
	// If the following call panics, it indicates UnimplementedManagementServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ManagementService_ServiceDesc, srv)
}

func _ManagementService_CreateAlgorithm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAlgorithmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).CreateAlgorithm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_CreateAlgorithm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).CreateAlgorithm(ctx, req.(*CreateAlgorithmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_UpdateAlgorithm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAlgorithmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).UpdateAlgorithm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_UpdateAlgorithm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).UpdateAlgorithm(ctx, req.(*UpdateAlgorithmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ListAlgorithms_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAlgorithmsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ListAlgorithms(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ListAlgorithms_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ListAlgorithms(ctx, req.(*ListAlgorithmsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetAlgorithm_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAlgorithmRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetAlgorithm(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetAlgorithm_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetAlgorithm(ctx, req.(*GetAlgorithmRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_CreateVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).CreateVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_CreateVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).CreateVersion(ctx, req.(*CreateVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_RollbackVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).RollbackVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_RollbackVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).RollbackVersion(ctx, req.(*RollbackVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_UploadPresetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).UploadPresetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_UploadPresetData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).UploadPresetData(ctx, req.(*UploadDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ListPresetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPresetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ListPresetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ListPresetData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ListPresetData(ctx, req.(*ListPresetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_DeletePresetData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePresetDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).DeletePresetData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_DeletePresetData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).DeletePresetData(ctx, req.(*DeletePresetDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_ListJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).ListJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_ListJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).ListJobs(ctx, req.(*ListJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetJobDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobDetailRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetJobDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetJobDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetJobDetail(ctx, req.(*GetJobDetailRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ManagementService_GetServerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServerInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ManagementServiceServer).GetServerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ManagementService_GetServerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ManagementServiceServer).GetServerInfo(ctx, req.(*GetServerInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ManagementService_ServiceDesc is the grpc.ServiceDesc for ManagementService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ManagementService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.ManagementService",
	HandlerType: (*ManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAlgorithm",
			Handler:    _ManagementService_CreateAlgorithm_Handler,
		},
		{
			MethodName: "UpdateAlgorithm",
			Handler:    _ManagementService_UpdateAlgorithm_Handler,
		},
		{
			MethodName: "ListAlgorithms",
			Handler:    _ManagementService_ListAlgorithms_Handler,
		},
		{
			MethodName: "GetAlgorithm",
			Handler:    _ManagementService_GetAlgorithm_Handler,
		},
		{
			MethodName: "CreateVersion",
			Handler:    _ManagementService_CreateVersion_Handler,
		},
		{
			MethodName: "RollbackVersion",
			Handler:    _ManagementService_RollbackVersion_Handler,
		},
		{
			MethodName: "UploadPresetData",
			Handler:    _ManagementService_UploadPresetData_Handler,
		},
		{
			MethodName: "ListPresetData",
			Handler:    _ManagementService_ListPresetData_Handler,
		},
		{
			MethodName: "DeletePresetData",
			Handler:    _ManagementService_DeletePresetData_Handler,
		},
		{
			MethodName: "ListJobs",
			Handler:    _ManagementService_ListJobs_Handler,
		},
		{
			MethodName: "GetJobDetail",
			Handler:    _ManagementService_GetJobDetail_Handler,
		},
		{
			MethodName: "GetServerInfo",
			Handler:    _ManagementService_GetServerInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/management.proto",
}
